- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
#    - !type:DepartmentTimeRequirement
#      department: Engineering
#      time: 36000 #10 hrs #_Ck 
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 36000 #10 hrs #_Ck
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 36000 #10 hrs #_Ck
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hrs
#    - !type:OverallPlaytimeRequirement
#      time: 54000 #15 hrs #_Ck
#    - !type:RoleTimeRequirement
#      role: JobHeadOfPersonnel
#      time: 7200 #2 hrs #_Ck
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  #start-backmen: currency
  minBankBalance: 400
  maxBankBalance: 600
  wageDepartment: Command
  wage: 100
  #end-backmen: currency
  special:
  - !type:AddComponentSpecial
    components:
      - type: PsionicBonusChance
        flatBonus: 0.025
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCaptain
    back: ClothingBackpackCaptainFilled
    shoes: ClothingShoesBootsLaceup
    head: ClothingHeadHatCaptain
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    outerClothing: ClothingOuterArmorCaptainCarapace
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  innerClothingSkirt: ClothingUniformJumpskirtCaptain
  satchel: ClothingBackpackSatchelCaptainFilled
  duffelbag: ClothingBackpackDuffelCaptainFilled
