- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:RoleTimeRequirement
      role: JobLawyer #_Ck
      time: 14400 # 4 hrs #_Ck
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Service
    - Brig
    - Maintenance
    - Command
    - External
    - CCGeneral
  #start-backmen: currency
  minBankBalance: 800
  maxBankBalance: 1200
  wageDepartment: Juridical
  wage: 200
  #end-backmen: currency
  special:
    - !type:AddImplantSpecial
      implants: [ MindShieldImplant ]
    - !type:AddComponentSpecial
      components:
        - type: SpecForce
          actionBssActionName: ActionCentcomFtlAction
        - type: Psionic

- type: startingGear
  id: IAAGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackIAAFilled
    shoes: ClothingShoesColorBlack
    id: IAAPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetIAA
    neck: ClothingNeckLawyerbadge
    pocket1: PaperFormAVD4
    pocket2: EncryptionKeyCentCom
  inhand:
    - BriefcaseIAAFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelIAAFilled
  duffelbag: ClothingBackpackDuffelIAAFilled
